var href=window.location.href;var mod_url=window.location.protocol+'//'+window.location.hostname;if(window.location.hostname=='localhost')
{mod_url='http://localhost/fvl';}
var showChar=250;var ellipsestext="...";var moretext="Show more";var lesstext="Show less";$('.more').each(function(){var content=jQuery(this).html();if(content.length>showChar){var c=content.substr(0,showChar);var h=content.substr(showChar,content.length-showChar);var html=c+'<span class="moreellipses">'+ellipsestext+'&nbsp;</span><span class="morecontent"><span>'+h+'</span>&nbsp;&nbsp;<a href="" class="morelink">'+moretext+'</a></span>';$(this).html(html);}});$(".morelink").click(function(){if(jQuery(this).hasClass("less")){jQuery(this).removeClass("less");jQuery(this).html(moretext);}else{jQuery(this).addClass("less");jQuery(this).html(lesstext);}
jQuery(this).parent().prev().toggle();jQuery(this).prev().toggle();return false;});function ChangeUrl(page,url){if(typeof(history.pushState)!="undefined"){var obj={Page:page,Url:url};history.pushState(obj,obj.Page,obj.Url);}else{alert("Browser does not support HTML5.");}}
$(document).on('click','.show_more',function(){var ID=$(this).attr('id');var course_attr=$(this).attr('course_attr');var recomm_attr=$(this).attr('recomm_attr');var cat_name=$('#cat_name_hidden').val();var uni_name=$('#uni_name_hidden').val();var tag_name=$('#tag_name_hidden').val();var search_name=$('#search_name_hidden').val();var recomment_name=$('#recomment_name').val();if(typeof cat_name!='undefined'){var cat_name=$('#cat_name_hidden').val();}else{var cat_name="";}
if(typeof uni_name!='undefined'){var uni_name=$('#uni_name_hidden').val();}else{var uni_name="";}
if(typeof tag_name!='undefined'){var tag_name=$('#tag_name_hidden').val();}else{var tag_name="";}
if(typeof search_name!='undefined'){var search_name=$('#search_name_hidden').val();}else{var search_name="";}
if(typeof recomment_name!='undefined'){var recomment_name=$('#recomment_name').val();}else{var recomment_name="";}
if($('#fvl_certi_val').is(":checked")){var checked_certi=$('#fvl_certi_val').val();}else{var checked_certi="";}
if($('#fvl_future_val').is(":checked")){var checked_future=$('#fvl_future_val').val();}else{var checked_future="";}
$('.show_more').hide();$('.loding').show();$.ajax({type:'POST',url:mod_url+'/ajaxFunctions.php',data:'function=subject_load&id='+ID+'&cat_name='+cat_name+'&course_attr='+course_attr+'&checked_certi='+checked_certi+'&checked_future='+checked_future+'&uni_name='+uni_name+'&tag_name='+tag_name+'&search_name='+search_name+'&recomment_name='+recomment_name+'&recomm_attr='+recomm_attr,success:function(html){$('#show_more_main'+ID).remove();$('#ajax_swaping').append(html);}});});$(window).scroll(function(){if($(this).scrollTop()>50){$('.totop a').fadeIn();}else{$('.totop a').fadeOut();$('header').css("display","block");}});$('.fvl_certified').change(function(){var cat_name=$("#cat_name_hidden").val();if($('#fvl_certi_val').is(":checked")){var checked_certi=$('#fvl_certi_val').val();}else{var checked_certi="";}
if($('#fvl_future_val').is(":checked")){var checked_future=$('#fvl_future_val').val();}else{var checked_future="";}
$('.more_load').hide();$('#cc_spinners').find('i.fa-spinner').show();$('#ajax_swaping').remove();$('.show_more_main').remove();$.ajax({type:"POST",url:mod_url+'/ajaxFunctions.php',data:"function=certified_course&checked_certi="+checked_certi+"&checked_future="+checked_future+"&cat_name="+cat_name,success:function(data){$('#cc_spinners').find('i.fa-spinner').hide();$('.more_load').show();$('#add_ajax').html(data);}});});$('.fvl_certified_uni').change(function(){var uni_name=$("#uni_name_hidden").val();if($('#fvl_certi_val').is(":checked")){var checked_certi=$('#fvl_certi_val').val();}else{var checked_certi="";}
if($('#fvl_future_val').is(":checked")){var checked_future=$('#fvl_future_val').val();}else{var checked_future="";}
$('.more_load').hide();$('#cc_spinners').find('i.fa-spinner').show();$('#ajax_swaping').remove();$('.show_more_main').remove();$.ajax({type:"POST",url:mod_url+'/ajaxFunctions.php',data:"function=certified_course_uni&checked_certi="+checked_certi+"&checked_future="+checked_future+"&uni_name="+uni_name,success:function(data){$('#cc_spinners').find('i.fa-spinner').hide();$('.more_load').show();$('#add_ajax').html(data);}});});$('.fvl_certified_tag').change(function(){var tag_name=$("#tag_name_hidden").val();if($('#fvl_certi_val').is(":checked")){var checked_certi=$('#fvl_certi_val').val();}else{var checked_certi="";}
if($('#fvl_future_val').is(":checked")){var checked_future=$('#fvl_future_val').val();}else{var checked_future="";}
$('.more_load').hide();$('#cc_spinners').find('i.fa-spinner').show();$('#ajax_swaping').remove();$('.show_more_main').remove();$.ajax({type:"POST",url:mod_url+'/ajaxFunctions.php',data:"function=certified_course_tag&checked_certi="+checked_certi+"&checked_future="+checked_future+"&tag_name="+tag_name,success:function(data){$('#cc_spinners').find('i.fa-spinner').hide();$('.more_load').show();$('#add_ajax').html(data);}});});$('.fvl_certified_search').change(function(){var search_name=$("#search_name_hidden").val();if($('#fvl_certi_val').is(":checked")){var checked_certi=$('#fvl_certi_val').val();}else{var checked_certi="";}
if($('#fvl_future_val').is(":checked")){var checked_future=$('#fvl_future_val').val();}else{var checked_future="";}
$('.more_load').hide();$('#cc_spinners').find('i.fa-spinner').show();$('#ajax_swaping').remove();$('.show_more_main').remove();$.ajax({type:"POST",url:mod_url+'/ajaxFunctions.php',data:"function=certified_course_search&checked_certi="+checked_certi+"&checked_future="+checked_future+"&search_name="+search_name,success:function(data){$('#cc_spinners').find('i.fa-spinner').hide();$('.more_load').show();$('#add_ajax').html(data);}});});$(document).on('click','.r_fav',function(){var c_id=$(this).data('id');var count_fav=parseInt($('.count_fav').html());var same=$(this);var result=confirm("Are you sure want to remove this list?");if(result){$.ajax({type:"POST",url:mod_url+'/ajaxFunctions.php',data:"function=remove_fav&c_id="+c_id,success:function(data){if(data!="success")
{alert(data);}
else
{if(count_fav==1)
{$('#count_fav').hide();}
$('.count_fav').html(count_fav-1);window.location.reload();}}});}
else
{return false;}});$("#submitcomment").click(function(){var comm_desc=$('#comm_desc').val();var user_id=$('#user_id').val();var securitycode=$('#security_code').val();$("#comment-message").css('display','none');$("#comment-message-error").css('display','none');$("#comment-message-errors").css('display','none');$("#comment-message-errorsmsg").css('display','none');$("#comment-message-login").css('display','none');if(user_id!=""&&user_id!=null){if($.trim(comm_desc).length>0){if(securitycode!=""){var course_id=$('#course_id').val();var lec_id=$('#lec_id').val();var user_id=$('#user_id').val();var user_name=$('#user_name').val();var comm_desc=$('#comm_desc').val();var securitycode=$('#security_code').val();$.ajax({type:'post',url:mod_url+'/ajaxcomment.php',data:"course_id="+course_id+"&lec_id="+lec_id+"&user_id="+user_id+"&user_name="+user_name+"&comm_desc="+comm_desc+"&securitycode="+securitycode,success:function(response)
{if(parseInt(response)==1)
{$("#comment-message").css('display','inline-block').fadeOut(5000);$("#comm_desc").val("");$("#security_code").val("");}
else if(parseInt(response)==2){$("#comment-message-errorsmsg").css('display','inline-block').fadeOut(5000);}
else
{alert("Failed to add comments !");return false;}}});}else{$("#comment-message-errors").css('display','inline-block').fadeOut(5000);}}else{$("#comment-message-error").css('display','inline-block').fadeOut(5000);}}else{$("#comment-message-login").css('display','inline-block');}});$('.all_fvl_certified').change(function(){if($('#fvl_certi_val').is(":checked")){var checked_certi=$('#fvl_certi_val').val();}else{var checked_certi="";}
if($('#fvl_future_val').is(":checked")){var checked_future=$('#fvl_future_val').val();}else{var checked_future="";}
$('.more_load').hide();$('#cc_spinners').find('i.fa-spinner').show();$('#ajax_swaping').remove();$('.show_more_main').remove();$.ajax({type:"POST",url:mod_url+'/ajaxFunctions.php',data:"function=all_certified_course&checked_certi="+checked_certi+"&checked_future="+checked_future,success:function(data){$('#cc_spinners').find('i.fa-spinner').hide();$('.more_load').show();$('#add_ajax').html(data);}});});$(document).ready(function(){$("#signup-form").submit(function(e){e.preventDefault();$("#status").show();var $form=$(this),name=$form.find('input[name="name"]').val(),email=$form.find('input[name="email"]').val(),url=$form.attr('action');var formName=$("#formName").val();$.post(url,{name:name,email:email,formName:formName},function(data){if(data)
{if(data=="Some fields are missing.")
{$("#status").text("Please fill in your name and email.");$("#status").css("color","red");}
else if(data=="Invalid email address.")
{$("#status").text("Your email address is invalid.");$("#status").css("color","red");}
else if(data=="Invalid list ID.")
{$("#status").text("Your list ID is invalid.");$("#status").css("color","red");}
else if(data=="Already subscribed.")
{$("#status").text("You're already subscribed!");$("#status").css("color","red");}
else
{$("#status").text("You're subscribed!").fadeOut(5000);$("#status").css("color","green");$("#signup-form")[0].reset();}}
else
{alert("Sorry, unable to subscribe. Please try again later!");}});});$("#signup-form").keypress(function(e){if(e.keyCode==13){e.preventDefault();$(this).submit();}});$("#submit-btn").click(function(e){e.preventDefault();$("#signup-form").submit();});});$(document).on('click','.r_compare',function(){var c_id=$(this).data('id');var count_compare=parseInt($('.count_compare').html());var same=$(this);var result=confirm("Are you sure want to remove this list?");if(result){$.ajax({type:"POST",url:mod_url+'/ajaxFunctions.php',data:"function=remove_compare&c_id="+c_id,success:function(data){if(data!="success")
{alert(data);}
else
{if(count_compare==1)
{$('#count_compare').hide();}
$('.count_compare').html(count_compare-1);same.parent('li').hide();window.location.reload();}}});}
else
{return false;}});$(document).on("click",".MarkComplete",function(){var Courselecid=$(".CourseLecID").val();var CourseId=$(".CourseID").val();var CourseName=$(".CourseName").val();var CourseLecNum=parseInt($(".CourseLecNUm").val());var CourseOrg=CourseLecNum+2;var button=$(this);$.ajax({type:"POST",url:mod_url+"/ajaxFunctions.php",data:"function=mark_complete_action&course_lecid="+Courselecid,success:function(data){button.attr('disabled',true);setTimeout(function(){window.location.href=mod_url+"/course/"+CourseId+"/"+CourseName+"/"+CourseOrg;},2000);}});});$(document).on("click",".EnrollMark",function(){var Courseid=$(".CourseID").val();var button=$(this);$.ajax({type:"POST",url:mod_url+"/ajaxFunctions.php",data:"function=enroll_action&course_id="+Courseid,success:function(data){button.hide();$(".EnrollSuccess").html("Successfully Enrolled!!").fadeOut(2000);$(".ElecturePlists").show(2000);}});});$(document).on("click","#EnrollCourses",function(){$(".WishLists").hide();$(".EnrollCourses").show();});$(document).on("click","#WishLists",function(){$(".WishLists").show();$(".EnrollCourses").hide();});$(document).on("click",".EnrollLoginSec",function(){window.location.href=mod_url+"/login.php";});